#!/usr/bin/env python3
"""
generate_icons.py — Resizes the generated app icon and installs it into
Android mipmap and iOS AppIcon asset directories.
"""
from PIL import Image
import os
import shutil

# --- Source icon (generated by AI) ---
SRC = "/home/gelnox/.gemini/antigravity/brain/774410cc-0250-42d0-9dd8-610bdda6a23c/app_icon_no_text_1784476355265.jpg"

# --- Android mipmap sizes ---
ANDROID_SIZES = {
    "mipmap-mdpi":    48,
    "mipmap-hdpi":    72,
    "mipmap-xhdpi":   96,
    "mipmap-xxhdpi":  144,
    "mipmap-xxxhdpi": 192,
}
ANDROID_RES = "/home/gelnox/project/android/app/src/main/res"

# --- iOS AppIcon sizes (points x scale) ---
IOS_SIZES = {
    "Icon-App-20x20@1x.png":      20,
    "Icon-App-20x20@2x.png":      40,
    "Icon-App-20x20@3x.png":      60,
    "Icon-App-29x29@1x.png":      29,
    "Icon-App-29x29@2x.png":      58,
    "Icon-App-29x29@3x.png":      87,
    "Icon-App-40x40@1x.png":      40,
    "Icon-App-40x40@2x.png":      80,
    "Icon-App-40x40@3x.png":      120,
    "Icon-App-60x60@2x.png":      120,
    "Icon-App-60x60@3x.png":      180,
    "Icon-App-76x76@1x.png":      76,
    "Icon-App-76x76@2x.png":      152,
    "Icon-App-83.5x83.5@2x.png":  167,
    "Icon-App-1024x1024@1x.png":  1024,
}
IOS_ICON_DIR = "/home/gelnox/project/ios/Runner/Assets.xcassets/AppIcon.appiconset"

def resize_and_save(src_path, dest_path, size):
    img = Image.open(src_path).convert("RGBA")
    img = img.resize((size, size), Image.LANCZOS)
    # Save as PNG
    img.save(dest_path, "PNG")
    print(f"  ✓ Saved {dest_path}  ({size}×{size})")

def main():
    print("=== My Reels Icon Generator ===\n")

    # --- Android ---
    print("[1] Installing Android mipmap icons...")
    for folder, size in ANDROID_SIZES.items():
        dest_dir = os.path.join(ANDROID_RES, folder)
        os.makedirs(dest_dir, exist_ok=True)
        dest = os.path.join(dest_dir, "ic_launcher.png")
        resize_and_save(SRC, dest, size)

    # --- iOS ---
    print("\n[2] Installing iOS AppIcon assets...")
    os.makedirs(IOS_ICON_DIR, exist_ok=True)
    for filename, size in IOS_SIZES.items():
        dest = os.path.join(IOS_ICON_DIR, filename)
        resize_and_save(SRC, dest, size)

    print("\n✅ All icons installed successfully!")

if __name__ == "__main__":
    main()
